### ISSUE TITLE
Problems with getting all the dependencies

### ISSUE THREAD

**Issue by TomTheDragon** [tskubicki/discord-xmpp#10]
I am not really quite sure if i just doing something wrong here, since i am still new to node.js but i have problems with getting all the dependencies to run this bot.

Here is a full log:
__________
npm http GET https://registry.npmjs.org/node-xmpp-client
npm http GET https://registry.npmjs.org/tinyurl
npm http GET https://registry.npmjs.org/discord.js
npm http 304 https://registry.npmjs.org/node-xmpp-client
npm http 304 https://registry.npmjs.org/tinyurl
npm http 304 https://registry.npmjs.org/discord.js
npm WARN engine discord.js@11.0.0: wanted: {"node":">=6.0.0"} (current: {"node":"v0.10.25","npm":"1.3.24"})
npm http GET https://registry.npmjs.org/browser-request
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/md5.js
npm http GET https://registry.npmjs.org/minimist
npm http GET https://registry.npmjs.org/node-xmpp-core
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/ws
npm http 304 https://registry.npmjs.org/browser-request
npm http 304 https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/md5.js
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/ws
npm http 304 https://registry.npmjs.org/node-xmpp-core
npm http 304 https://registry.npmjs.org/minimist
npm WARN engine request@2.81.0: wanted: {"node":">= 4"} (current: {"node":"v0.10.25","npm":"1.3.24"})
npm http GET https://registry.npmjs.org/hash-base
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/lodash.assign
npm http GET https://github.com/dodo/reconnect-core/tarball/merged
npm http GET https://registry.npmjs.org/node-xmpp-tls-connect
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/hash-base
npm http GET https://registry.npmjs.org/xmpp/jid
npm http GET https://registry.npmjs.org/xmpp/streamparser
npm http GET https://registry.npmjs.org/xmpp/xml
npm http 304 https://registry.npmjs.org/lodash.assign
npm http 304 https://registry.npmjs.org/node-xmpp-tls-connect
npm http GET https://registry.npmjs.org/ms/0.7.2
npm http GET https://registry.npmjs.org/aws-sign2
npm http GET https://registry.npmjs.org/aws4
npm http GET https://registry.npmjs.org/caseless
npm http GET https://registry.npmjs.org/combined-stream
npm http GET https://registry.npmjs.org/extend
npm http 304 https://registry.npmjs.org/ms/0.7.2
npm http GET https://registry.npmjs.org/forever-agent
npm http GET https://registry.npmjs.org/form-data
npm http GET https://registry.npmjs.org/har-validator
npm http GET https://registry.npmjs.org/hawk
npm http GET https://registry.npmjs.org/http-signature
npm http 304 https://registry.npmjs.org/aws4
npm http GET https://registry.npmjs.org/is-typedarray
npm http GET https://registry.npmjs.org/isstream
npm http GET https://registry.npmjs.org/json-stringify-safe
npm http GET https://registry.npmjs.org/mime-types
npm http GET https://registry.npmjs.org/ultron
npm http GET https://registry.npmjs.org/oauth-sign
npm http GET https://registry.npmjs.org/performance-now
npm http GET https://registry.npmjs.org/qs
npm http GET https://registry.npmjs.org/options
npm http GET https://registry.npmjs.org/stringstream
npm http GET https://registry.npmjs.org/safe-buffer
npm http GET https://registry.npmjs.org/tough-cookie
npm http GET https://registry.npmjs.org/tunnel-agent
npm http 304 https://registry.npmjs.org/caseless
npm http GET https://registry.npmjs.org/uuid
npm http 304 https://registry.npmjs.org/combined-stream
npm http 304 https://registry.npmjs.org/extend
npm http 304 https://registry.npmjs.org/forever-agent
npm http 304 https://registry.npmjs.org/aws-sign2
npm http 304 https://registry.npmjs.org/form-data
npm http 304 https://registry.npmjs.org/har-validator
npm http 304 https://registry.npmjs.org/hawk
npm http 304 https://registry.npmjs.org/http-signature
npm http 304 https://registry.npmjs.org/is-typedarray
npm http 304 https://registry.npmjs.org/isstream
npm http 304 https://registry.npmjs.org/json-stringify-safe
npm http 304 https://registry.npmjs.org/mime-types
npm http 304 https://registry.npmjs.org/ultron
npm http 304 https://registry.npmjs.org/oauth-sign
npm http 304 https://registry.npmjs.org/performance-now
npm http 304 https://registry.npmjs.org/options
npm http 304 https://registry.npmjs.org/qs
npm http 304 https://registry.npmjs.org/stringstream
npm http 304 https://registry.npmjs.org/safe-buffer
npm http 304 https://registry.npmjs.org/tough-cookie
npm http 304 https://registry.npmjs.org/tunnel-agent
npm http 304 https://registry.npmjs.org/uuid
npm WARN engine form-data@2.1.4: wanted: {"node":">= 0.12"} (current: {"node":"v0.10.25","npm":"1.3.24"})
npm WARN engine har-validator@4.2.1: wanted: {"node":">=4"} (current: {"node":"v0.10.25","npm":"1.3.24"})
npm WARN engine hawk@3.1.3: wanted: {"node":">=0.10.32"} (current: {"node":"v0.10.25","npm":"1.3.24"})
npm http 404 https://registry.npmjs.org/xmpp/jid
npm http 404 https://registry.npmjs.org/xmpp/streamparser
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/local/lib/node_modules/npm/lib/cache.js:692:35)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:680:5
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save"
npm ERR! cwd /home/user/discord-xmpp
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! type non_object_property_load
npm http 404 https://registry.npmjs.org/xmpp/xml
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/local/lib/node_modules/npm/lib/cache.js:692:35)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:680:5
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save"
npm ERR! cwd /home/user/discord-xmpp
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! type non_object_property_load
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/local/lib/node_modules/npm/lib/cache.js:692:35)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:680:5
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save"
npm ERR! cwd /home/user/discord-xmpp
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! type non_object_property_load
npm http GET https://registry.npmjs.org/delayed-stream
npm http GET https://registry.npmjs.org/mime-db
npm http 304 https://registry.npmjs.org/delayed-stream
npm http 304 https://registry.npmjs.org/mime-db
npm http GET https://registry.npmjs.org/asynckit
npm http 304 https://registry.npmjs.org/asynckit
npm http GET https://registry.npmjs.org/assert-plus
npm http GET https://registry.npmjs.org/jsprim
npm http GET https://registry.npmjs.org/sshpk
npm http GET https://registry.npmjs.org/ajv
npm http GET https://registry.npmjs.org/har-schema
npm http 304 https://registry.npmjs.org/jsprim
npm http 304 https://registry.npmjs.org/assert-plus
npm http 304 https://registry.npmjs.org/sshpk
npm http 304 https://registry.npmjs.org/har-schema
npm http 304 https://registry.npmjs.org/ajv
npm WARN engine har-schema@1.0.5: wanted: {"node":">=4"} (current: {"node":"v0.10.25","npm":"1.3.24"})
npm http GET https://registry.npmjs.org/json-schema/0.2.3
npm http GET https://registry.npmjs.org/verror/1.3.6
npm http GET https://registry.npmjs.org/assert-plus/1.0.0
npm http GET https://registry.npmjs.org/extsprintf/1.0.2
npm http 304 https://registry.npmjs.org/json-schema/0.2.3
npm http 304 https://registry.npmjs.org/verror/1.3.6
npm http 304 https://registry.npmjs.org/assert-plus/1.0.0
npm http 304 https://registry.npmjs.org/extsprintf/1.0.2
npm http 200 https://github.com/dodo/reconnect-core/tarball/merged
npm http GET https://registry.npmjs.org/punycode
npm http 304 https://registry.npmjs.org/punycode
npm http GET https://registry.npmjs.org/pako
npm http GET https://registry.npmjs.org/superagent
npm http GET https://registry.npmjs.org/tweetnacl
npm http GET https://registry.npmjs.org/types/node
npm http 304 https://registry.npmjs.org/superagent
npm http 304 https://registry.npmjs.org/tweetnacl
npm http 304 https://registry.npmjs.org/pako
npm http GET https://registry.npmjs.org/asn1
npm http GET https://registry.npmjs.org/dashdash
npm http GET https://registry.npmjs.org/getpass
npm http GET https://registry.npmjs.org/jsbn
npm http GET https://registry.npmjs.org/hoek
npm http GET https://registry.npmjs.org/boom
npm http GET https://registry.npmjs.org/cryptiles
npm http GET https://registry.npmjs.org/sntp
npm http GET https://registry.npmjs.org/jodid25519
npm http GET https://registry.npmjs.org/bcrypt-pbkdf
npm http GET https://registry.npmjs.org/ecc-jsbn
npm http 304 https://registry.npmjs.org/asn1
npm http 304 https://registry.npmjs.org/hoek
npm http 304 https://registry.npmjs.org/dashdash
npm http 304 https://registry.npmjs.org/boom
npm http 304 https://registry.npmjs.org/getpass
npm http 304 https://registry.npmjs.org/sntp
npm http 304 https://registry.npmjs.org/cryptiles
npm http 304 https://registry.npmjs.org/jsbn
npm http 304 https://registry.npmjs.org/jodid25519
npm http 304 https://registry.npmjs.org/bcrypt-pbkdf
npm http 304 https://registry.npmjs.org/ecc-jsbn
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"v0.10.25","npm":"1.3.24"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"v0.10.25","npm":"1.3.24"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"v0.10.25","npm":"1.3.24"})
npm http 404 https://registry.npmjs.org/types/node
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/local/lib/node_modules/npm/lib/cache.js:692:35)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:680:5
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save"
npm ERR! cwd /home/user/discord-xmpp
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! type non_object_property_load
npm http GET https://registry.npmjs.org/co
npm http GET https://registry.npmjs.org/json-stable-stringify
npm http 304 https://registry.npmjs.org/co
npm http 304 https://registry.npmjs.org/json-stable-stringify
npm WARN engine co@4.6.0: wanted: {"iojs":">= 1.0.0","node":">= 0.12.0"} (current: {"node":"v0.10.25","npm":"1.3.24"})
npm http GET https://registry.npmjs.org/jsonify
npm http 304 https://registry.npmjs.org/jsonify
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/user/discord-xmpp/npm-debug.log
npm ERR! not ok code 0
__________

I use Debian 8 (amd64)

**Comment by tskubicki** [comment]
Hi Tom.

Can you try installing the latest version of node.js and trying it again?
A lot of the dependencies are leaning on there being a recent version of it.

Thanks.

**Comment by TomTheDragon** [comment]
Thx for the tip Tskubicki
I had to try around a bit but i finally got it to work.
I still get warnings but it still seems to run fine.

**Comment by tskubicki** [comment]
Feel free to reach out if you are having any issues.
Best.
