### ISSUE TITLE
Unable to connect discord

### ISSUE THREAD

**Issue by djyumene** [tskubicki/discord-xmpp#3]
This might be something simple, but I am stuck in a completely different issue than the other post.  This is what I'm getting:

root@server1:~/fconping/discord-xmpp# nodejs app.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'discord.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/fconping/discord-xmpp/app.js:14:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

**Comment by djyumene** [comment]
Disreguard, I was in the wrong folder
