### ISSUE TITLE
TypeError: Cannot read property 'sendMessage' of undefined

### ISSUE THREAD

**Issue by kernelpanic3** [tskubicki/discord-xmpp#8]
Hi,

Trying to use this as a read-only relay between the server [here](http://mesonet.agron.iastate.edu/projects/iembot/) and a Discord server. The bot connects without issue, but after a minute or two throws this exception and crashes:

```
/home/calvin/discord-xmpp/app.js:181
                discord.channel.sendMessage(message);
                               ^

TypeError: Cannot read property 'sendMessage' of undefined
    at Client.<anonymous> (/home/calvin/discord-xmpp/app.js:181:18)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:188:7)
    at Client._handleStanza (/home/calvin/discord-xmpp/node_modules/node-xmpp-client/lib/Client.js:227:12)
    at Client.onStanza (/home/calvin/discord-xmpp/node_modules/node-xmpp-client/lib/Client.js:221:8)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:188:7)
    at Connection.onStanza (/home/calvin/discord-xmpp/node_modules/node-xmpp-core/lib/Connection.js:377:10)
    at StreamParser.<anonymous> (/home/calvin/discord-xmpp/node_modules/node-xmpp-core/lib/Connection.js:231:10)
    at emitOne (events.js:96:13)
```

Am I doing something wrong here, or did I just unearth a bug?

Thanks for a useful script!

**Comment by tskubicki** [comment]
Hi kernelpanic!

My "Successfully connected" checks haven't been very thorough, so its possible something slipped through.

Can you fill in line 174 with the following and paste what it gives back just before the error?
console.log(discord.channel);

Thanks!

**Comment by kernelpanic3** [comment]
Hi, and thanks for your quick response!

Here is the full output, start to finish:

```
calvin@goldenoaks:~/discord-xmpp$ node app.js
Successfully connected to Discord.
Successfully authenticated with ngawxrelay@conference.weather.im
Successfully connected to XMPP chatroom 'botstalk@conference.weather.im'.
undefined
/home/calvin/discord-xmpp/app.js:181
                discord.channel.sendMessage(message);
                               ^

TypeError: Cannot read property 'sendMessage' of undefined
    at Client.<anonymous> (/home/calvin/discord-xmpp/app.js:181:18)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:188:7)
    at Client._handleStanza (/home/calvin/discord-xmpp/node_modules/node-xmpp-client/lib/Client.js:227:12)
    at Client.onStanza (/home/calvin/discord-xmpp/node_modules/node-xmpp-client/lib/Client.js:221:8)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:188:7)
    at Connection.onStanza (/home/calvin/discord-xmpp/node_modules/node-xmpp-core/lib/Connection.js:377:10)
    at StreamParser.<anonymous> (/home/calvin/discord-xmpp/node_modules/node-xmpp-core/lib/Connection.js:231:10)
    at emitOne (events.js:96:13)
```

**Comment by tskubicki** [comment]
Thanks.

Can you try that again after changing that line to this:
console.log(discord);

**Comment by kernelpanic3** [comment]
```
Successfully authenticated with ngawxrelay@conference.weather.im
Successfully connected to Discord.
Successfully connected to XMPP chatroom 'botstalk@conference.weather.im'.
Client {
  domain: null,
  _events:
   { 'self.voiceServer': [Function: bound onVoiceServer],
     'self.voiceStateUpdate': [Function: bound onVoiceStateUpdate],
     ready: [ [Function] ],
     message: [Function],
     error: [Function] },
  _eventsCount: 5,
  _maxListeners: undefined,
  options:
   { autoReconnect: true,
     apiRequestMethod: 'sequential',
     shardId: 0,
     shardCount: 0,
     messageCacheMaxSize: 200,
     messageCacheLifetime: 0,
     messageSweepInterval: 0,
     fetchAllMembers: false,
     disableEveryone: false,
     sync: false,
     restWsBridgeTimeout: 5000,
     disabledEvents: [],
     restTimeOffset: 500,
     ws:
      { large_threshold: 250,
        compress: true,
        properties: [Object],
        token: 'Mjk5NTE0Mjk3MDU3MjgwMDAw.C8e_8g.LDKHwPDgbcJXfHP6FPnnxOS82BM' } },
  rest:
   RESTManager {
     client: [Circular],
     handlers: { 'https://discordapp.com/api/v6/gateway': [Object] },
     userAgentManager: UserAgentManager { restManager: [Circular], _userAgent: [Object] },
     methods: RESTMethods { rest: [Circular], client: [Circular] },
     rateLimitedEndpoints: {},
     globallyRateLimited: false },
  dataManager: ClientDataManager { client: [Circular] },
  manager:
   ClientManager {
     client: [Circular],
     heartbeatInterval:
      Timeout {
        _called: false,
        _idleTimeout: 41250,
        _idlePrev: [Object],
        _idleNext: [Object],
        _idleStart: 1241,
        _onTimeout: [Function],
        _timerArgs: undefined,
        _repeat: 41250 } },
  ws:
   WebSocketManager {
     domain: null,
     _events: { close: [Object] },
     _eventsCount: 1,
     _maxListeners: undefined,
     client: [Circular],
     packetManager: WebSocketPacketManager { ws: [Circular], handlers: [Object], queue: [] },
     status: 0,
     sessionID: '69973ad9b9dfc1a70f386485cf7d4fa0',
     sequence: 1,
     gateway: 'wss://gateway.discord.gg/?v=6',
     normalReady: true,
     ws:
      WebSocket {
        domain: null,
        _events: [Object],
        _eventsCount: 4,
        _maxListeners: undefined,
        _socket: [Object],
        _ultron: [Object],
        _closeReceived: false,
        bytesReceived: 442,
        readyState: 1,
        supports: [Object],
        extensions: {},
        _binaryType: 'nodebuffer',
        _isServer: false,
        url: 'wss://gateway.discord.gg/?v=6&encoding=json',
        protocolVersion: 13,
        _receiver: [Object],
        _sender: [Object] },
     disabledEvents: {},
     first: false,
     lastHeartbeatAck: true,
     _queue: [],
     _remaining: 119,
     reconnecting: false },
  resolver: ClientDataResolver { client: [Circular] },
  actions:
   ActionsManager {
     client: [Circular],
     MessageCreate: MessageCreateAction { client: [Circular] },
     MessageDelete: MessageDeleteAction { client: [Circular], deleted: Map {} },
     MessageDeleteBulk: MessageDeleteBulkAction { client: [Circular] },
     MessageUpdate: MessageUpdateAction { client: [Circular] },
     MessageReactionAdd: MessageReactionAdd { client: [Circular] },
     MessageReactionRemove: MessageReactionRemove { client: [Circular] },
     MessageReactionRemoveAll: MessageReactionRemoveAll { client: [Circular] },
     ChannelCreate: ChannelCreateAction { client: [Circular] },
     ChannelDelete: ChannelDeleteAction { client: [Circular], deleted: Map {} },
     ChannelUpdate: ChannelUpdateAction { client: [Circular] },
     GuildDelete: GuildDeleteAction { client: [Circular], deleted: Map {} },
     GuildUpdate: GuildUpdateAction { client: [Circular] },
     GuildMemberGet: GuildMemberGetAction { client: [Circular] },
     GuildMemberRemove: GuildMemberRemoveAction { client: [Circular], deleted: Map {} },
     GuildBanRemove: GuildBanRemove { client: [Circular] },
     GuildRoleCreate: GuildRoleCreate { client: [Circular] },
     GuildRoleDelete: GuildRoleDeleteAction { client: [Circular], deleted: Map {} },
     GuildRoleUpdate: GuildRoleUpdateAction { client: [Circular] },
     UserGet: UserGetAction { client: [Circular] },
     UserUpdate: UserUpdateAction { client: [Circular] },
     UserNoteUpdate: UserNoteUpdateAction { client: [Circular] },
     GuildSync: GuildSync { client: [Circular] },
     GuildEmojiCreate: GuildEmojiCreateAction { client: [Circular] },
     GuildEmojiDelete: GuildEmojiDeleteAction { client: [Circular] },
     GuildEmojiUpdate: GuildEmojiUpdateAction { client: [Circular] },
     GuildRolesPositionUpdate: GuildRolesPositionUpdate { client: [Circular] } },
  voice:
   ClientVoiceManager {
     client: [Circular],
     connections: Collection { _array: null, _keyArray: null },
     pending: Collection { _array: null, _keyArray: null } },
  shard: null,
  users:
   Collection {
     '299514297057280000' => ClientUser {
     id: '299514297057280000',
     username: 'IEMBot Live Relay',
     discriminator: '9677',
     avatar: '2ad09b12b4216a89d4a8fe6b59a075b5',
     bot: true,
     lastMessageID: null,
     verified: true,
     email: null,
     localPresence: {},
     _typing: Map {},
     friends: [Object],
     blocked: [Object],
     notes: [Object] },
     '1' => User {
     id: '1',
     username: 'Clyde',
     discriminator: '0000',
     avatar: 'https://discordapp.com/assets/f78426a064bc9dd24847519259bc42af.png',
     bot: true,
     lastMessageID: null },
     _array: null,
     _keyArray: null },
  guilds: Collection { _array: null, _keyArray: null },
  channels: Collection { _array: null, _keyArray: null },
  presences: Collection { _array: null, _keyArray: null },
  token: 'Mjk5NTE0Mjk3MDU3MjgwMDAw.C8e_8g.LDKHwPDgbcJXfHP6FPnnxOS82BM',
  user:
   ClientUser {
     id: '299514297057280000',
     username: 'IEMBot Live Relay',
     discriminator: '9677',
     avatar: '2ad09b12b4216a89d4a8fe6b59a075b5',
     bot: true,
     lastMessageID: null,
     verified: true,
     email: null,
     localPresence: {},
     _typing: Map {},
     friends: Collection { _array: null, _keyArray: null },
     blocked: Collection { _array: null, _keyArray: null },
     notes: Collection { _array: null, _keyArray: null } },
  readyAt: 2017-04-06T16:45:59.521Z,
  pings: [ 63 ],
  _pingTimestamp: 1491497159520,
  _timeouts: Set {},
  _intervals:
   Set {
     Timeout {
     _called: false,
     _idleTimeout: 60000,
     _idlePrev: [Object],
     _idleNext: [Object],
     _idleStart: 1030,
     _onTimeout: [Function],
     _timerArgs: undefined,
     _repeat: 60000 },
     Timeout {
     _called: false,
     _idleTimeout: 41250,
     _idlePrev: [Object],
     _idleNext: [Object],
     _idleStart: 1241,
     _onTimeout: [Function],
     _timerArgs: undefined,
     _repeat: 41250 } },
  channel: undefined }
/home/calvin/discord-xmpp/app.js:181
                discord.channel.sendMessage(message);
                               ^

TypeError: Cannot read property 'sendMessage' of undefined
    at Client.<anonymous> (/home/calvin/discord-xmpp/app.js:181:18)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:188:7)
    at Client._handleStanza (/home/calvin/discord-xmpp/node_modules/node-xmpp-client/lib/Client.js:227:12)
    at Client.onStanza (/home/calvin/discord-xmpp/node_modules/node-xmpp-client/lib/Client.js:221:8)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:188:7)
    at Connection.onStanza (/home/calvin/discord-xmpp/node_modules/node-xmpp-core/lib/Connection.js:377:10)
    at StreamParser.<anonymous> (/home/calvin/discord-xmpp/node_modules/node-xmpp-core/lib/Connection.js:231:10)
    at emitOne (events.js:96:13)
```

It seems I skipped over the most important step: authorizing the bot to join the server. Oops...it runs now. Maybe it just needs some handling for morons like me who skip steps.

(I still have another unrelated issue...but I'll make a new ticket for that.)

Sorry for wasting your time!

**Comment by tskubicki** [comment]
No worries. Let me know what that issue is when you're ready.

Thanks.
